ximu_torso:
 origin: [-0.15,0.05,0.0]
ximu_pelvis:
 origin: [-0.15,-0.05,0.0]
ximu_femur_l:
 origin: [-0.05,0.05,0.0]
ximu_femur_r:
 origin: [-0.05,-0.05,0.0]
ximu_tibia_l:
 origin: [0.05,0.05,0.0]
ximu_tibia_r:
 origin: [0.05,-0.05,0]
ximu_talus_l:
 origin: [0.15,0.05,0.0]
ximu_talus_r:
 origin: [0.15,-0.05,0]
